// feeds using rrs2json
export const FeedsUrl = [
  {
    id: 1,
    name: 'Coin Desk',
    symbol: 'coindesk',
    url: 'https%3A%2F%2Fwww.coindesk.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 2,
    name: 'Coin Telegraph',
    symbol: 'cointelegraph',
    url: 'https%3A%2F%2Fcointelegraph.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 3,
    name: 'AMB Crypto',
    symbol: 'ambcrypto',
    url: 'https%3A%2F%2Feng.ambcrypto.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 4,
    name: 'Bitcoin Magazine',
    symbol: 'bitcoinmagazine',
    url: 'https%3A%2F%2Fbitcoinmagazine.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 5,
    name: 'News BTC',
    symbol: 'newsbtc',
    url: 'https%3A%2F%2Fwww.newsbtc.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 6,
    name: 'Bit Coinist',
    symbol: 'bitcoinist',
    url: 'https%3A%2F%2Fbitcoinist.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 7,
    name: 'The Block Crypto',
    symbol: 'theblockcrypto',
    url: 'https%3A%2F%2Fwww.theblockcrypto.com%2Frss.xml',
    bookmark: false,
  },
  {
    id: 8,
    name: 'Bitcoin Exchange Guide',
    symbol: 'bitcoinexchangeguide',
    url: 'https%3A%2F%2Fbitcoinexchangeguide.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 9,
    name: 'Block Onomi',
    symbol: 'blockonomi',
    url: 'https%3A%2F%2Fblockonomi.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 10,
    name: 'cryptoSlate',
    symbol: 'cryptoslate',
    url: 'https%3A%2F%2Fcryptoslate.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 11,
    name: 'BTC Manager',
    symbol: 'btcmanager',
    url: 'https%3A%2F%2Fbtcmanager.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 12,
    name: 'Inside Bitcoins',
    symbol: 'insidebitcoins',
    url: 'https%3A%2F%2Finsidebitcoins.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 13,
    name: 'Coin Speaker',
    symbol: 'coinspeaker',
    url: 'https%3A%2F%2Fwww.coinspeaker.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 14,
    name: 'Crypto News',
    symbol: 'cryptonews',
    url: 'https%3A%2F%2Fcryptonews.com%2Fnews%2Ffeed',
    bookmark: false,
  },
  {
    id: 15,
    name: 'Crypto Briefling',
    symbol: 'cryptobriefing',
    url: 'https%3A%2F%2Fcryptobriefing.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 16,
    name: 'Crypto Potato',
    symbol: 'cryptopotato',
    url: 'https%3A%2F%2Fcryptopotato.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 17,
    name: 'Daily Hodl',
    symbol: 'dailyhodl',
    url: 'https%3A%2F%2Fdailyhodl.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 18,
    name: 'Coin Journal',
    symbol: 'coinjournal',
    url: 'https%3A%2F%2Fcoinjournal.net%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 19,
    name: 'Ethereum World News',
    symbol: 'ethereumworldnews',
    url: 'https%3A%2F%2Fen.ethereumworldnews.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 20,
    name: 'Crypto Ninjas',
    symbol: 'cryptoninjas',
    url: 'http%3A%2F%2Fwww.cryptoninjas.net%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 21,
    name: 'Coin Center',
    symbol: 'coincenter',
    url: 'https%3A%2F%2Fwww.coincenter.org%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 22,
    name: 'Bein Crypto',
    symbol: 'beincrypto',
    url: 'https%3A%2F%2Fbeincrypto.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 23,
    name: 'The BitCoin News',
    symbol: 'thebitcoinnews',
    url: 'https%3A%2F%2Fthebitcoinnews.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 24,
    name: 'Coin Geek',
    symbol: 'coingeek',
    url: 'https%3A%2F%2Fcoingeek.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 25,
    name: 'Coin Gape',
    symbol: 'coingape',
    url: 'https%3A%2F%2Fcoingape.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 26,
    name: 'Live Bitcoin News',
    symbol: 'livebitcoinnews',
    url: 'https%3A%2F%2Fwww.livebitcoinnews.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 27,
    name: 'Trust Nodes',
    symbol: 'trustnodes',
    url: 'https%3A%2F%2Fwww.trustnodes.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 28,
    name: 'Null Tx',
    symbol: 'nulltx',
    url: 'https%3A%2F%2Fnulltx.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 29,
    name: 'Coin Idol',
    symbol: 'coinidol',
    url: 'https%3A%2F%2Fcoinidol.com%2Frss2%2F',
    bookmark: false,
  },
  {
    id: 30,
    name: 'Invest Block Chain',
    symbol: 'investblockchain',
    url: 'https%3A%2F%2Fwww.investinblockchain.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 31,
    name: 'Bits Online',
    symbol: 'bitsonline',
    url: 'https%3A%2F%2Fbitsonline.com%2Ffeed%2F',
    bookmark: false,
  },
  // {
  //   id: 32,
  //   name: 'Crypto Daily',
  //   symbol: 'cryptodaily',
  //   url: 'https%3A%2F%2Fcryptodaily.co.uk%2Ffeed',
  // bookmark: false,
  // },
  {
    id: 33,
    name: 'Block Tribune',
    symbol: 'blocktribune',
    url: 'https%3A%2F%2Fblocktribune.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 34,
    name: 'Zycrypto',
    symbol: 'zycrypto',
    url: 'https%3A%2F%2Fzycrypto.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 35,
    name: 'Use the Bitcoin',
    symbol: 'usethebitcoin',
    url: 'https%3A%2F%2Fusethebitcoin.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 36,
    name: 'Smart Etereum',
    symbol: 'smartereum',
    url: 'https%3A%2F%2Fsmartereum.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 37,
    name: 'Bitcoin Garden',
    symbol: 'bitcoingarden',
    url: 'https%3A%2F%2Fbitcoingarden.org%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 38,
    name: 'Block Manity',
    symbol: 'blockmanity',
    url: 'https%3A%2F%2Fblockmanity.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 39,
    name: 'Coin Pedia',
    symbol: 'coinpedia',
    url: 'https%3A%2F%2Fcoinpedia.org%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 40,
    name: 'Forklog',
    symbol: 'forklog',
    url: 'https%3A%2F%2Fforklog.media%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 41,
    name: 'Alt Coin Buzz',
    symbol: 'altcoinbuzz',
    url: 'https%3A%2F%2Fwww.altcoinbuzz.io%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 42,
    name: 'Coin Fox',
    symbol: 'coinfox',
    url:
      'http%3A%2F%2Fwww.coinfox.info%2F%3Foption%3Dcom_content%26view%3Dfeatured%26Itemid%3D160%26format%3Dfeed%26type%3Drss',
    bookmark: false,
  },
  {
    id: 43,
    name: 'Feed Burner',
    symbol: 'kryptomoney',
    url: 'http%3A%2F%2Ffeeds.feedburner.com%2Fkryptomoney',
    bookmark: false,
  },
  {
    id: 44,
    name: 'Bitcoin News',
    symbol: 'bitcoinnews',
    url: 'https%3A%2F%2Fbitcoinnews.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 45,
    name: 'Bitcoin Warrior',
    symbol: 'bitcoinwarrior',
    url: 'https%3A%2F%2Fbitcoinwarrior.net%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 46,
    name: 'Btc Wires',
    symbol: 'btcwires',
    url: 'https%3A%2F%2Fwww.btcwires.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 47,
    name: 'Coin Revolution',
    symbol: 'coinrevolution',
    url: 'https%3A%2F%2Fwww.coinrevolution.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 48,
    name: 'Coin Staker',
    symbol: 'coinstaker',
    url: 'https%3A%2F%2Fwww.coinstaker.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 49,
    name: 'Bitcoin Pr Buzz',
    symbol: 'bitcoinprbuzz',
    url: 'https%3A%2F%2Fbitcoinprbuzz.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 50,
    name: 'Coin News Asia',
    symbol: 'coinnewsasia',
    url: 'https%3A%2F%2Fwww.coinnewsasia.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 51,
    name: 'News 8 btc',
    symbol: '8btc',
    url: 'https%3A%2F%2Fnews.8btc.com%2Ffeed',
    bookmark: false,
  },
  {
    id: 52,
    name: '7 Bitcoins',
    symbol: '7bitcoins',
    url: 'https%3A%2F%2Fwww.7bitcoins.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 53,
    name: 'DC Forecasts',
    symbol: 'dcforecasts',
    url: 'https://www.dcforecasts.com/feed/',
    bookmark: false,
  },
  {
    id: 54,
    name: 'Coin Delite',
    symbol: 'coindelite',
    url: 'https://www.dcforecasts.com/feed/',
    bookmark: false,
  },
  {
    id: 55,
    name: 'Global Crypto Press',
    symbol: 'globalcryptopress',
    url: 'https%3A%2F%2Fwww.globalcryptopress.com%2Ffeeds%2Fposts%2Fdefault',
    bookmark: false,
  },
  {
    id: 56,
    name: 'Crypto Core Media',
    symbol: 'cryptocoremedia',
    url: 'https%3A%2F%2Fcryptocoremedia.com%2Ffeed%2F',
    bookmark: false,
  },
  {
    id: 57,
    name: 'Block Chain Today',
    symbol: 'blockchaintoday',
    url: 'https%3A%2F%2Fblockchaintd.com%2Frss.xml',
    bookmark: false,
  },
  {
    id: 58,
    name: 'Finance Magnates',
    symbol: 'financemagnates',
    url: 'https%3A%2F%2Fwww.financemagnates.com%2Ffeed%2F',
    bookmark: false,
  },
];
