// feeds using rrs2json
export const FeedsUrl = [
  {
    id: 1,
    name: 'Coin Desk',
    symbol: 'coindesk.png',
    url: 'https%3A%2F%2Fwww.coindesk.com%2Ffeed',
  },
  {
    id: 2,
    name: 'Coin Telegraph',
    symbol: 'cointelegraph.png',
    url: 'https%3A%2F%2Fcointelegraph.com%2Ffeed',
  },
  {
    id: 3,
    name: 'AMB Crypto',
    symbol: 'ambcrypto.png',
    url: 'https%3A%2F%2Feng.ambcrypto.com%2Ffeed%2F',
  },
  {
    id: 4,
    name: 'Bitcoin Magazine',
    symbol: 'bitcoinmagazine.png',
    url: 'https%3A%2F%2Fbitcoinmagazine.com%2Ffeed',
  },
  {
    id: 5,
    name: 'News BTC',
    symbol: 'newsbtc.png',
    url: 'https%3A%2F%2Fwww.newsbtc.com%2Ffeed%2F',
  },
  {
    id: 6,
    name: 'Bit Coinist',
    symbol: 'bitcoinist.png',
    url: 'https%3A%2F%2Fbitcoinist.com%2Ffeed%2F',
  },
  {
    id: 7,
    name: 'The Block Crypto',
    symbol: 'theblockcrypto.png',
    url: 'https%3A%2F%2Fwww.theblockcrypto.com%2Frss.xml',
  },
  {
    id: 8,
    name: 'Bitcoin Exchange Guide',
    symbol: 'bitcoinexchangeguide.png',
    url: 'https%3A%2F%2Fbitcoinexchangeguide.com%2Ffeed%2F',
  },
  {
    id: 9,
    name: 'Block Onomi',
    symbol: 'blockonomi.png',
    url: 'https%3A%2F%2Fblockonomi.com%2Ffeed%2F',
  },
  {
    id: 10,
    name: 'cryptoSlate',
    symbol: 'cryptoslate.png',
    url: 'https%3A%2F%2Fcryptoslate.com%2Ffeed%2F',
  },
  {
    id: 11,
    name: 'BTC Manager',
    symbol: 'btcmanager.png',
    url: 'https%3A%2F%2Fbtcmanager.com%2Ffeed',
  },
  {
    id: 12,
    name: 'Inside Bitcoins',
    symbol: 'insidebitcoins.png',
    url: 'https%3A%2F%2Finsidebitcoins.com%2Ffeed',
  },
  {
    id: 13,
    name: 'Coin Speaker',
    symbol: 'coinspeaker.png',
    url: 'https%3A%2F%2Fwww.coinspeaker.com%2Ffeed%2F',
  },
  {
    id: 14,
    name: 'Crypto News',
    symbol: 'cryptonews.png',
    url: 'https%3A%2F%2Fcryptonews.com%2Fnews%2Ffeed',
  },
  {
    id: 15,
    name: 'Crypto Briefling',
    symbol: 'cryptobriefing.png',
    url: 'https%3A%2F%2Fcryptobriefing.com%2Ffeed%2F',
  },
  {
    id: 16,
    name: 'Crypto Potato',
    symbol: 'cryptopotato.png',
    url: 'https%3A%2F%2Fcryptopotato.com%2Ffeed%2F',
  },
  {
    id: 17,
    name: 'Daily Hodl',
    symbol: 'dailyhodl.png',
    url: 'https%3A%2F%2Fdailyhodl.com%2Ffeed%2F',
  },
  {
    id: 18,
    name: 'Coin Journal',
    symbol: 'coinjournal.png',
    url: 'https%3A%2F%2Fcoinjournal.net%2Ffeed%2F',
  },
  {
    id: 19,
    name: 'Ethereum World News',
    symbol: 'ethereumworldnews.png',
    url: 'https%3A%2F%2Fen.ethereumworldnews.com%2Ffeed%2F',
  },
  {
    id: 20,
    name: 'Crypto Ninjas',
    symbol: 'cryptoninjas.png',
    url: 'http%3A%2F%2Fwww.cryptoninjas.net%2Ffeed%2F',
  },
  {
    id: 21,
    name: 'Coin Center',
    symbol: 'coincenter.png',
    url: 'https%3A%2F%2Fwww.coincenter.org%2Ffeed%2F',
  },
  {
    id: 22,
    name: 'Bein Crypto',
    symbol: 'beincrypto.png',
    url: 'https%3A%2F%2Fbeincrypto.com%2Ffeed%2F',
  },
  {
    id: 23,
    name: 'The BitCoin News',
    symbol: 'thebitcoinnews.png',
    url: 'https%3A%2F%2Fthebitcoinnews.com%2Ffeed%2F',
  },
  {
    id: 24,
    name: 'Coin Geek',
    symbol: 'coingeek.png',
    url: 'https%3A%2F%2Fcoingeek.com%2Ffeed%2F',
  },
  {
    id: 25,
    name: 'Coin Gape',
    symbol: 'coingape.png',
    url: 'https%3A%2F%2Fcoingape.com%2Ffeed%2F',
  },
  {
    id: 26,
    name: 'Live Bitcoin News',
    symbol: 'livebitcoinnews.png',
    url: 'https%3A%2F%2Fwww.livebitcoinnews.com%2Ffeed%2F',
  },
  {
    id: 27,
    name: 'Trust Nodes',
    symbol: 'trustnodes.png',
    url: 'https%3A%2F%2Fwww.trustnodes.com%2Ffeed%2F',
  },
  {
    id: 28,
    name: 'Null Tx',
    symbol: 'nulltx.png',
    url: 'https%3A%2F%2Fnulltx.com%2Ffeed%2F',
  },
  {
    id: 29,
    name: 'Coin Idol',
    symbol: 'coinidol.png',
    url: 'https%3A%2F%2Fcoinidol.com%2Frss2%2F',
  },
  {
    id: 30,
    name: 'Invest Block Chain',
    symbol: 'investblockchain.png',
    url: 'https%3A%2F%2Fwww.investinblockchain.com%2Ffeed%2F',
  },
  {
    id: 31,
    name: 'Bits Online',
    symbol: 'bitsonline.png',
    url: 'https%3A%2F%2Fbitsonline.com%2Ffeed%2F',
  },
  {
    id: 32,
    name: 'Crypto Daily',
    symbol: 'bitsonline.png',
    url: 'https%3A%2F%2Fcryptodaily.co.uk%2Ffeed',
  },
  {
    id: 33,
    name: 'Block Tribune',
    symbol: 'blocktribune.png',
    url: 'https%3A%2F%2Fblocktribune.com%2Ffeed',
  },
  {
    id: 34,
    name: 'Zycrypto',
    symbol: 'zycrypto.png',
    url: 'https%3A%2F%2Fzycrypto.com%2Ffeed%2F',
  },
  {
    id: 35,
    name: 'Use the Bitcoin',
    symbol: 'zycrypto.png',
    url: 'https%3A%2F%2Fusethebitcoin.com%2Ffeed%2F',
  },
  {
    id: 36,
    name: 'Smart Etereum',
    symbol: 'smartereum.png',
    url: 'https%3A%2F%2Fsmartereum.com%2Ffeed%2F',
  },
  {
    id: 37,
    name: 'Bitcoin Garden',
    symbol: 'bitcoingarden.png',
    url: 'https%3A%2F%2Fbitcoingarden.org%2Ffeed%2F',
  },
  {
    id: 38,
    name: 'Block Manity',
    symbol: 'blockmanity.png',
    url: 'https%3A%2F%2Fblockmanity.com%2Ffeed%2F',
  },
  {
    id: 39,
    name: 'Coin Pedia',
    symbol: 'blockmanity.png',
    url: 'https%3A%2F%2Fcoinpedia.org%2Ffeed%2F',
  },
  {
    id: 40,
    name: 'Forklog',
    symbol: 'forklog.png',
    url: 'https%3A%2F%2Fforklog.media%2Ffeed%2F',
  },
  {
    id: 41,
    name: 'Alt Coin Buzz',
    symbol: 'altcoinbuzz.png',
    url: 'https%3A%2F%2Fwww.altcoinbuzz.io%2Ffeed%2F',
  },
  {
    id: 42,
    name: 'Coin Fox',
    symbol: 'coinfox.png',
    url:
      'http%3A%2F%2Fwww.coinfox.info%2F%3Foption%3Dcom_content%26view%3Dfeatured%26Itemid%3D160%26format%3Dfeed%26type%3Drss',
  },
  {
    id: 42,
    name: 'Feed Burner',
    symbol: 'coinfox.png',
    url: 'http%3A%2F%2Ffeeds.feedburner.com%2Fkryptomoney',
  },
  {
    id: 45,
    name: 'Bitcoin News',
    symbol: 'bitcoinnews.png',
    url: 'https%3A%2F%2Fbitcoinnews.com%2Ffeed%2F',
  },
  {
    id: 46,
    name: 'Bitcoin Warrior',
    symbol: 'bitcoinwarrior.png',
    url: 'https%3A%2F%2Fbitcoinwarrior.net%2Ffeed%2F',
  },
  {
    id: 47,
    name: 'Btc Wires',
    symbol: 'btcwires.png',
    url: 'https%3A%2F%2Fwww.btcwires.com%2Ffeed%2F',
  },
  {
    id: 48,
    name: 'Coin Revolution',
    symbol: 'btcwires.png',
    url: 'https%3A%2F%2Fwww.coinrevolution.com%2Ffeed%2F',
  },
  {
    id: 49,
    name: 'Coin Staker',
    symbol: 'coinstaker.png',
    url: 'https%3A%2F%2Fwww.coinstaker.com%2Ffeed%2F',
  },
  {
    id: 50,
    name: 'Bitcoin Pr Buzz',
    symbol: 'bitcoinprbuzz.png',
    url: 'https%3A%2F%2Fbitcoinprbuzz.com%2Ffeed%2F',
  },
  {
    id: 51,
    name: 'Coin News Asia',
    symbol: 'coinnewsasia.png',
    url: 'https%3A%2F%2Fwww.coinnewsasia.com%2Ffeed%2F',
  },
  {
    id: 52,
    name: 'News 8 btc',
    symbol: '8btc.png',
    url: 'https%3A%2F%2Fnews.8btc.com%2Ffeed',
  },
  {
    id: 53,
    name: '7 Bitcoins',
    symbol: '7bitcoins.png',
    url: 'https%3A%2F%2Fwww.7bitcoins.com%2Ffeed%2F',
  },
  {
    id: 54,
    name: 'DC Forecasts',
    symbol: '7bitcoins.png',
    url: 'https://www.dcforecasts.com/feed/',
  },
  {
    id: 55,
    name: 'Coin Delite',
    symbol: '7bitcoins.png',
    url: 'https://www.dcforecasts.com/feed/',
  },
  {
    id: 56,
    name: 'Global Crypto Press',
    symbol: 'globalcryptopress.png',
    url: 'https%3A%2F%2Fwww.globalcryptopress.com%2Ffeeds%2Fposts%2Fdefault',
  },
  {
    id: 57,
    name: 'Crypto Core Media',
    symbol: 'cryptocoremedia.png',
    url: 'https%3A%2F%2Fcryptocoremedia.com%2Ffeed%2F',
  },
  {
    id: 58,
    name: 'Block Chain Today',
    symbol: 'blockchaintoday.png',
    url: 'https%3A%2F%2Fblockchaintd.com%2Frss.xml',
  },
  {
    id: 59,
    name: 'Finance Magnates',
    symbol: 'financemagnates.png',
    url: 'https%3A%2F%2Fwww.financemagnates.com%2Ffeed%2F',
  },
];
