language: node_js
node_js:
  - '10'

branches:
  only:
    - master

addons:
  chrome: stable

before script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  # - ng lint
  # - ng test --watch=false
  - ng build --prod --base-href="https://mkortmann.github.io/Crypto-Tracker/ && angular-cli-ghpages --branch gh-pages"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
  - ngh --branch=gh-pages --no-silent
