language: node_js
node_js:
  - '10'

branches:
  - master
  - gh-pages

addons:
  chrome: stable

before script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod --base-href="https://mkortmann.github.io/Crypto-Tracker/"
  - ngh --dir dist/crypto-tracker --no-silent
