language: node_js
node_js:
  - '10'

branches:
  - master
  - gh-pages

addons:
  chrome: stable

before script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - echo $TRAVIS_COMMIT
  - echo $CI_COMMIT_SHORT_SHA
  - ng lint
  - ng test --watch=false
  - ng build --prod --base-href="https://mkortmann.github.io/Crypto-Tracker/"
  - sed -i "s/%%version%%/$TRAVIS_COMMIT/g" ./dist/crypto-tracker/index.html
  - ngh --dir dist/crypto-tracker --no-silent
