language: node_js
node_js:
  - '10'

branches:
  only:
    - master

addons:
  chrome: stable

before script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod --base-href="https://mkortmann.github.io/Crypto-Tracker/"
  - ngh --dir dist/crypto-tracker
