language: node_js
node_js:
  - '10'
cache: npm

branches:
  only:
    - master

addons:
  chrome: stable

install:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod --base-href="https://mkortmann.github.io/Crypto-Tracker/ && angular-cli-ghpages --branch gh-pages"

  deploy:
    provider: pages
    github-token: $GITHUB_TOKEN
    on:
      branch: gh-pages

